/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as libBoardSol from "./LibBoard.sol";
export type { libBoardSol };
export type { MEGAETH2048 } from "./MEGAETH2048";
export * as factories from "./factories";
export type { Board } from "./LibBoard.sol/Board";
export { Board__factory } from "./factories/LibBoard.sol/Board__factory";
export { MEGAETH2048__factory } from "./factories/MEGAETH2048__factory";
