/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as libBoardSol from "./LibBoard.sol";
export { MEGAETH2048__factory } from "./MEGAETH2048__factory";
